# Generated by Django 3.1.6 on 2021-06-01 16:46

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Society', '0001_initial'),
        ('User', '0002_auto_20210601_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park_slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_status', models.CharField(blank=True, choices=[('1', 'Free'), ('3', 'Requested'), ('2', 'Booked')], default='1', max_length=255)),
                ('has_owner', models.BooleanField(blank=True)),
                ('is_reserved_slot', models.BooleanField(blank=True)),
                ('slot_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True)),
                ('langitude', models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.society')),
            ],
        ),
        migrations.CreateModel(
            name='Park_Slot_Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'Please enter your name'}, max_length=30)),
                ('address', models.CharField(error_messages={'required': 'Please enter your address'}, max_length=50)),
                ('city', models.CharField(error_messages={'required': 'Please enter your city'}, max_length=30)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(default='+91', max_length=128, region=None, unique=True)),
                ('email', models.EmailField(default='', max_length=30, unique=True)),
                ('password', models.CharField(default='', max_length=20)),
                ('aadhar_card', models.FileField(upload_to='Building_Owner/Docs/')),
                ('aadhar_num', models.BigIntegerField()),
                ('bank_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('account_number', models.BigIntegerField(unique=True)),
                ('ifsc_code', models.CharField(max_length=50, unique=True)),
                ('cancel_check', models.ImageField(upload_to='Building_Owner/Docs/')),
                ('commision', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('park_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zone.park_slot')),
            ],
        ),
        migrations.CreateModel(
            name='Zone_Booking_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField()),
                ('checkin_date', models.DateField(blank=True)),
                ('checkout_date', models.DateField(blank=True)),
                ('checkin_time', models.TimeField(blank=True)),
                ('checkout_time', models.TimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Zone_Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(blank=True)),
                ('activated_package_expire', models.DateField(blank=True)),
                ('booking_arrival_time', models.TimeField(blank=True)),
                ('booking_departure_time', models.TimeField(blank=True)),
                ('activated_package', models.CharField(choices=[('Weekly', 'Weekly'), ('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Monthly', 'Monthly')], default='', max_length=30)),
                ('booking_amount', models.FloatField(blank=True, default=0.0)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('booking_status', models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Requested', 'Requested'), ('Booked', 'Booked')], max_length=30)),
                ('no_of_booking', models.IntegerField(blank=True, default=0.0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('park_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zone.park_slot')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.uservehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Park_Slot_Owner_Commision_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(blank=True)),
                ('payment_status', models.CharField(blank=True, max_length=50)),
                ('amount', models.FloatField(blank=True)),
                ('commision_paid_amount', models.FloatField()),
                ('commision_due_amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('park_slot_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zone.park_slot_owner')),
            ],
        ),
    ]
