# Generated by Django 3.0.5 on 2022-09-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park_slot',
            name='availability_status',
            field=models.CharField(blank=True, choices=[('3', 'Requested'), ('2', 'Booked'), ('1', 'Free')], default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='zone_booking',
            name='activated_package',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Daily', 'Daily')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='zone_booking',
            name='booking_status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Booked', 'Booked'), ('Requested', 'Requested')], max_length=30),
        ),
    ]
