# Generated by Django 3.0.5 on 2022-09-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkZoneApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_wallet',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('2', 'Due'), ('1', 'Paid')], max_length=50),
        ),
    ]
