# Generated by Django 3.1.6 on 2021-06-01 16:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(default='India', error_messages={'required': 'Please enter your country'}, max_length=30)),
                ('two_wheel_hourly_price', models.FloatField()),
                ('two_wheel_weekly_price', models.FloatField()),
                ('two_wheel_monthly_price', models.FloatField()),
                ('two_wheel_daily_price', models.FloatField()),
                ('four_wheel_hourly_price', models.FloatField()),
                ('four_wheel_weekly_price', models.FloatField()),
                ('four_wheel_monthly_price', models.FloatField()),
                ('four_wheel_daily_price', models.FloatField()),
                ('number_of_parking', models.IntegerField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('longtitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('langtitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('bank_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('account_number', models.BigIntegerField(unique=True)),
                ('ifsc_code', models.CharField(max_length=50, unique=True)),
                ('cancel_check', models.ImageField(upload_to='Society_Secretry/Docs/')),
                ('commision', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Society_Secretry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=30)),
                ('country', models.CharField(default='', max_length=30)),
                ('state', models.CharField(default='', max_length=30)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(default='+91', max_length=128, region=None, unique=True)),
                ('email', models.EmailField(default='', max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('aadhar_card', models.FileField(upload_to='Society_Secretry/Docs/')),
                ('aadhar_num', models.BigIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('society', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Society.society')),
            ],
        ),
        migrations.CreateModel(
            name='Society_Commision_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(blank=True)),
                ('payment_status', models.CharField(blank=True, max_length=50)),
                ('amount', models.FloatField(blank=True)),
                ('commision_paid_amount', models.FloatField(blank=True)),
                ('commision_due_amount', models.FloatField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.society')),
            ],
        ),
    ]
