# Generated by Django 3.1.6 on 2021-06-01 16:46

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Society', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=30)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(default='+91', max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(default='', max_length=20)),
                ('aadhar_card', models.FileField(null=True, upload_to='Watchman/Documents')),
                ('aadhar_num', models.CharField(max_length=12)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='WatchMan/Images')),
                ('salary', models.FloatField()),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('society', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Society.society')),
            ],
        ),
        migrations.CreateModel(
            name='Watchman_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(blank=True)),
                ('payment_status', models.CharField(blank=True, max_length=50)),
                ('salary', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('watchman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Watchman.watchman')),
            ],
        ),
    ]
