# Generated by Django 3.1.6 on 2021-06-01 16:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(default='+91', max_length=128, region=None, unique=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('password', models.CharField(blank=True, max_length=20)),
                ('confirm_password', models.CharField(blank=True, max_length=20)),
                ('facebook_token', models.CharField(blank=True, max_length=200)),
                ('google_token', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Wallet_bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('1', '2 Wheeler'), ('2', '4 Wheeler')], max_length=30)),
                ('vehicle_registration_no', models.CharField(max_length=18)),
                ('type_of_model', models.CharField(blank=True, default='', max_length=30)),
                ('color', models.CharField(blank=True, default='', max_length=30)),
                ('rc_book_no', models.CharField(blank=True, max_length=30)),
                ('rc_book_front_file', models.ImageField(blank=True, upload_to='User/VehicleDocs/')),
                ('rc_book_back_file', models.ImageField(blank=True, upload_to='User/VehicleDocs/')),
                ('driving_lic_number', models.CharField(blank=True, default='', max_length=15)),
                ('driving_lic_photo', models.ImageField(blank=True, upload_to='User/VehicleDocs/')),
                ('refferal_user_num', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='User_Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('transaction_type', models.CharField(blank=True, max_length=30)),
                ('transaction_amount', models.FloatField(blank=True, default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='User_Transaction_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(blank=True, default=0.0, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=30)),
                ('transaction_amount', models.FloatField(blank=True, default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('user_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user_wallet')),
            ],
        ),
        migrations.CreateModel(
            name='User_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(blank=True, choices=[('Wallet', 'Wallet'), ('Vehicle', 'Vehicle'), ('Profile', 'Profile'), ('Booking', 'Booking')], max_length=300)),
                ('act_date', models.DateField(blank=True, null=True)),
                ('act_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
