# Generated by Django 3.1.6 on 2021-06-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_activity',
            name='category',
            field=models.CharField(blank=True, choices=[('Wallet', 'Wallet'), ('Vehicle', 'Vehicle'), ('Booking', 'Booking'), ('Profile', 'Profile')], max_length=300),
        ),
    ]
