# Generated by Django 3.0.5 on 2022-09-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210601_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_activity',
            name='category',
            field=models.CharField(blank=True, choices=[('Vehicle', 'Vehicle'), ('Wallet', 'Wallet'), ('Profile', 'Profile'), ('Booking', 'Booking')], max_length=300),
        ),
    ]
